spring:
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      generate-ddl: false
      open-in-view: false
      show-sql: true
      hibernate:
         ddl-auto: none
         use-new-id-generator-mappings: true
      properties:
         hibernate.id.new_generator_mappings: true
         hibernate.cache.use_second_level_cache: false
         hibernate.cache.use_query_cache: true
         hibernate.generate_statistics: false
   datasource:
      type: com.zaxxer.hikari.HikariDataSource
       #dataSourceClassName: org.postgresql.Driver
      url: jdbc:postgresql://10.247.185.10:5432/anudaan?currentSchema=soch
      username: soch_train_app_user
      password: S0chApP2020
      hikari:
        poolName: Hikari
logging:
   level:
       root: error
       org: error
       gov: error
notification:
   emailServiceUrl: http://localhost:8080/notification/sendemail/
   systemEmailServiceUrl: http://localhost:8085/notification/sendsystememail/
   smsServiceUrl: http://localhost:8080/notification/sendsms/
   systemSmsServiceUrl: http://localhost:8080/notification/sendsystemsms/
   whatsappServiceUrl: http://localhost:8080/notification/sendwhatsapp/
   webuserNotificationUrl: http://localhost:8085/notification/webnotification/send/ 
sso:
  manager:
    url: http://13.234.85.91:1978/ssosession
cache:
  clearEndpointsAdmin: http://localhost:8080/admin/system/clearCache
accessKey: devkey@3
captchaEnabled: true
captchaEnabledForMobile: false
disclaimerFrequencyDays: 30
crossDomainAllowedOrigins: https://sochtraining.naco.gov.in
jwtSecret: U09DSCtUMHBTM2NyRXQrQXV0aG9yaXphdGlvbit0b2tlbitrZXk=
kylinUrl: https://kylin.uat.projectsoch.org/kylin/
ssoEnabled: true
exportRecordsLimit: 50000
serverLoggingUrl: https://sochtraining.naco.gov.in/training/api/logs
ssoDomain: sochtraining.naco.gov.in
validateByOtpEnabled: false