spring:
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      generate-ddl: false
      open-in-view: false
      show-sql: false
      hibernate:
         ddl-auto: none
      properties:
         hibernate.id.new_generator_mappings: true
         hibernate.cache.use_second_level_cache: false
         hibernate.cache.use_query_cache: true
         hibernate.generate_statistics: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #dataSourceClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/soch-db-dev?currentSchema=soch
    username: postgres
    password: postgres
    hikari:
        poolName: Hikari
  ldap:
    urls: ldap://13.127.24.42:389
    base: dc=project-qasoch,dc=org
    username: cn=ldapadmin,dc=project-qasoch,dc=org
    password: Ldap@123
logging:
   level:
       root: error
       org: error
       gov: error
notification:
  emailServiceUrl: http://localhost:8080/notification/sendemail/
  systemEmailServiceUrl: http://localhost:8085/notification/sendsystememail/
  smsServiceUrl: http://localhost:8080/notification/sendsms/
  systemSmsServiceUrl: http://localhost:8080/notification/sendsystemsms/
  whatsappServiceUrl: http://localhost:8080/notification/sendwhatsapp/
  webuserNotificationUrl: http://localhost:8085/notification/webnotification/send/
sso:
  manager:
    url: http://13.127.24.42:1978/ssosession
cache:
  clearEndpointsAdmin: http://localhost:8080/admin/system/clearCache
accessKey: devkey@3
captchaEnabled: true
captchaEnabledForMobile: false
disclaimerFrequencyDays: 30
crossDomainAllowedOrigins: http://localhost:4200,https://52.136.112.194,https://3.7.182.184,https://projectsoch.org,https://project-qasoch.org,https://15.207.231.130
jwtSecret: U09DSCtIZTExMFMzY3crRG9udDN2M3J0cjF0MGYhbmRNMyt3QHJuIW5nKy4=
kylinUrl: https://kylin.project-qasoch.org/kylin/
ssoEnabled: true
exportRecordsLimit: 50000
serverLoggingUrl: http://10.153.156.132/prod/api/logs
ssoDomain: projectsoch.org
validateByOtpEnabled: false