spring:
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      generate-ddl: false
      open-in-view: false
      show-sql: true
      hibernate:
         ddl-auto: none
         default-schema: anudan
      properties:
         hibernate.id.new_generator_mappings: true
         hibernate.cache.use_second_level_cache: false
         hibernate.cache.use_query_cache: true
         hibernate.generate_statistics: false
         hibernate.default_schema: anudan
   datasource:
       type: com.zaxxer.hikari.HikariDataSource
       #dataSourceClassName: org.postgresql.Driver
       url: jdbc:postgresql://10.247.185.11:9999/soch_stag_app_db?currentSchema=anudan
       username: soch_stag_app_user
       password: S0chApP2020
       hikari:
        poolName: Hikari
   ldap:
       urls: ldap://10.247.185.13:389
       base: dc=projectsoch,dc=org
       username: cn=ldapadmin,dc=projectsoch,dc=org
       password: Ldap@123           
logging:
   level:
       root: info
       org: info
       gov: info
notification:
   emailServiceUrl: http://localhost:8085/notification/sendemail/
   systemEmailServiceUrl: http://localhost:8085/notification/sendsystememail/
   smsServiceUrl: http://localhost:8085/notification/sendsms/
   whatsappServiceUrl: http://localhost:8085/notification/sendwhatsapp/
   webuserNotificationUrl: http://localhost:8085/notification/webnotification/send/  
   systemSmsServiceUrl: http://localhost:8085/notification/sendsystemsms/  
sso:
  manager:
    url: http://34.212.135.8:1978/ssosession
cache:
  clearEndpointsAdmin: http://localhost:8080/admin/system/clearCache
accessKey: devkey@3
captchaEnabled: true
captchaEnabledForMobile: false
disclaimerFrequencyDays: 30
crossDomainAllowedOrigins: http://10.247.185.13,https://sochbeta.naco.gov.in
jwtSecret: U09DSCtUMHBTM2NyRXQrQXV0aG9yaXphdGlvbit0b2tlbitrZXk=
kylinUrl: https://kylin.uat.projectsoch.org/kylin/
ssoEnabled: true   
exportRecordsLimit: 50000
serverLoggingUrl: https://sochbeta.naco.gov.in/staging/api/logs
ssoDomain: naco.gov.in
validateByOtpEnabled: false