spring:
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      generate-ddl: false
      open-in-view: false
      show-sql: true
      hibernate:
         ddl-auto: none
         use-new-id-generator-mappings: true
      properties:
         hibernate.id.new_generator_mappings: true
         hibernate.cache.use_second_level_cache: false
         hibernate.cache.use_query_cache: true
         hibernate.generate_statistics: false
   datasource:
       type: com.zaxxer.hikari.HikariDataSource
       #dataSourceClassName: org.postgresql.Driver
       url: jdbc:postgresql://localhost:5432/soch-db-dev?currentSchema=soch
       username: postgres
       password: postgres
       hikari:
        poolName: Hikari
   ldap:
    urls: ldap://13.127.24.42:389
    base: dc=project-qasoch,dc=org
    username: cn=ldapadmin,dc=project-qasoch,dc=org
    password: Ldap@123
logging:
   level:
       root: info
       org: info
       gov: info
notification:
   emailServiceUrl: http://localhost:8085/notification/sendemail/
   systemEmailServiceUrl: http://localhost:8085/notification/sendsystememail/
   smsServiceUrl: http://localhost:8085/notification/sendsms/
   systemSmsServiceUrl: http://localhost:8085/notification/sendsystemsms/
   whatsappServiceUrl: http://localhost:8085/notification/sendwhatsapp/
   webuserNotificationUrl: http://localhost:8085/notification/webnotification/send/
sso:
  manager:
    url: http://13.127.24.42:1978/ssosession
cache:
  clearEndpointsAdmin: http://localhost:8080/admin/system/clearCache
accessKey: devkey@3
captchaEnabled: true
captchaEnabledForMobile: false
disclaimerFrequencyDays: 30
crossDomainAllowedOrigins:
jwtSecret: U09DSCtUMHBTM2NyRXQrQXV0aG9yaXphdGlvbit0b2tlbitrZXk=
kylinUrl: https://kylin.uat.projectsoch.org/kylin/
ssoEnabled: true    
exportRecordsLimit: 50000
serverLoggingUrl: https://15.206.121.67/uat/api/logs
ssoDomain: project-qasoch.org
validateByOtpEnabled: false